15 hit is a percussion (and tickets 7, 8, 9)
rivten/handmadefighter pull request #13
Opened 2016-11-17 22:00 UTC by khoadot

7 ship freezes, 8 ship teleports after hitlag, 10 ship knows the side of the hit

2016-11-17 22:12 UTC, khoadot commented
⚠️ Si ça fail, regarder staticbox, normalement la scène n'a plus de script associé

2016-11-17 22:51 UTC, rivten requested changes
Je suis pas sûr d'avoir tout bien compris, en tout cas quand je teste chez moi, il arrive pas à charger le code pour la statichitbox (à raison puisque ce code n'existe plus)

2016-11-17 22:51 UTC, rivten commented on code/static_hitbox.gd
> -extends Area2D
Je crois que je comprends pas où est-ce que ce code est passé.

2016-11-17 22:51 UTC, rivten commented on Fighter.tscn
> +extents = Vector2( 10, 10 )
Quand je chope ça chez moi, j'ai l'impression que ça a fait décaler toute la scène... T'as ça toi aussi ?

2016-11-17 22:51 UTC, rivten commented on code/fighter.gd
> -func _draw():
On dessine plus ?

2016-11-21 15:00 UTC, khoadot commented on code/fighter.gd
> -func _draw():
nope, maintenant qu'on a une projection, on a de quoi prouver que notre vaisseau sait de quel côté il a été touché :)

2016-11-21 15:01 UTC, khoadot commented on Fighter.tscn
> +extents = Vector2( 10, 10 )
euh je sais pas je peux pas regarder now 😕

2016-11-21 15:01 UTC, khoadot commented on code/static_hitbox.gd
> -extends Area2D
It is gone on purpose.

2016-11-22 00:18 UTC, rivten approved these changes

2016-11-22 00:19 UTC, merged