42 make hit get away from homeline
rivten/handmadefighter pull request #24
Opened 2016-11-26 15:47 UTC by rivten

2016-11-29 00:18 UTC, khoadot commented on code/fighter.gd
> +	move(DeltaFreezePos + DeltaHitPos)
_Functional issue : _
Actually my wording of the ticket was not clear : by saying the hit has the fighter "décalé" I meant it to ~~teleport~~ **project** towards the front.
So you may undo the changes here and make the following change, later in the file : 
```
	if (LastHitSide == "left"):
		HitDirection = Vector2(0, 1) + 0.5 * BulletDir
	else: # LastHitSide == "right"
		HitDirection = Vector2(0, -1) + 0.5 * BulletDir
```

2016-11-29 00:21 UTC, khoadot requested changes
The behaviour is not what I had in mind ; the change is easy though please see my comment

2016-11-29 09:17 UTC, rivten commented
Fixed. I just want to point something out. In gameplay programming, there is a constant tradeoff two be found between two things : (A) controlling the exact position of an object, but not its movement equation (unless its mov. equation is trivial)  (B) controlling the object movement equation but not its exact position

In that case, I can either know my hit acceleration or my hit DeltaPos, it depends on what I want to control.

2016-11-30 15:49 UTC, khoadot approved these changes

2016-11-30 15:49 UTC, merged