9 make hitbox respawn if disappeared
rivten/handmadefighter pull request #7
Opened 2016-11-14 18:21 UTC by khoadot

2016-11-14 18:48 UTC, rivten requested changes
Je suis pas d'accord avec tout.

2016-11-14 18:48 UTC, rivten commented on code/game.gd
> -	Hitbox.set_pos(Vector2(0, -120))
`set_pos(HitboxInitialPos)`

2016-11-14 18:48 UTC, rivten commented on code/game.gd
> +var HitboxWr
Appelle ça `HitboxWeakref` non ? Je suis toujours partisant du verbose à mois que le sens de la contraction soit **absolument évident**. Ca prends pas tellement plus de temps et c'est mille fois plus clair pour le lecteur.

En outre est-ce qu'il y a vraiment besoin d'une weakref ? Je suis pas sûr de voir pourquoi. Ca ne te sert qu'à storer un état mais jamais tu lis dans cet état.

2016-11-14 18:48 UTC, rivten commented on code/game.gd
> +func OnTimerTimeout():
faudrait vite décider d'une convention : 
`OnTimerTimeout` ou bien `on_timer_timeout`. D'habitude je suis partisan du premier, mais avec Godot qui force l'écriture du second, ça pourrait être bien de remettre ça en question.

2016-11-14 18:54 UTC, rivten requested changes
Quelques petits changements

2016-11-14 18:54 UTC, rivten commented on code/static_hitbox.gd
> +	if (get_overlapping_bodies() != []):
De mémoire, `_fixed_process(dt)` est un meilleur choix pour la gestion de la physique de `_process(dt)`
Peut être que `if(!get_overlapping_bodies().empty())` est plus clair, non ? C'est un choix après.

2016-11-14 23:36 UTC, khoadot commented on code/game.gd
> +var HitboxWr
Si, je lis dans OnTimerTimeout.
Et totalement d'accord pour le nommage normalement je suis très pointilleux dessus.

2016-11-14 23:38 UTC, khoadot commented on code/static_hitbox.gd
> +	if (get_overlapping_bodies() != []):
+ ok je connais pas la différence…
+ ok plus clair je suis 100% d'accord je connaissais pas cette méthode

2016-11-15 00:17 UTC, khoadot commented on code/game.gd
> -	Hitbox.set_pos(Vector2(0, -120))
je ne comprends pas ce commentaire

2016-11-15 00:20 UTC, khoadot commented on code/game.gd
> +func OnTimerTimeout():
on s'est mis d'accord sur le_casing_avec_underscore.
Et l'autre truc avec lequel je suis pas d'accord avec ce que j'ai fait c'est  que je préfère grave nommer la fonction par ce qu'elle fait, pas par quand elle est appelée ou whatevs

2016-11-15 00:41 UTC, merged